name: Packer CI - AMI Build

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.repository == 'NEU-Cloud-CSYE6225/webapp'
    steps:
    - uses: actions/checkout@v3

    - name: Archive the Repository
      run: |
        zip -r app.zip AssignmentsAPI

    - name: Create .env
      run: |
        echo PORT=${{ secrets.PORT }} >> .env
        echo DB_HOST={{ secrets.DB_HOST }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
    
    - name: Setup Packer
      run: |
        curl -Lo packer.zip https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
        unzip packer.zip
        sudo mv packer /usr/local/bin/

    - name: Initialize Packer
      run: packer init aws-debian.pkr.hcl

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build AMI
      run: packer build aws-debian.pkr.hcl
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        PORT: ${{ secrets.PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Retrieve AMI ID
      run: |
        AMI_ID=$(jq -r '.builds[0].artifact_id' manifest.json | cut -d ':' -f 2)
        echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

    - name: Share AMI with DEMO Account
      run: |
        DEMO_ACCOUNT_ID="565864190124"
        aws ec2 modify-image-attribute --image-id ${{ env.AMI_ID }} --launch-permission "Add=[{UserId=$DEMO_ACCOUNT_ID}]"
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AMI_ID: ${{ env.AMI_ID }}

