name: Packer CI - Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Prepare Application zip
      run: |
        zip -r app.zip AssignmentsAPI

    - name: Setup Packer
      run: |
        curl -Lo packer.zip https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
        unzip packer.zip
        sudo mv packer /usr/local/bin/

    - name: Initialize Packer
      run: packer init aws-debian.pkr.hcl

    - name: Packer Format Check
      run: |
        packer fmt -check aws-debian.pkr.hcl

    - name: Packer Validate
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
      run: packer validate aws-debian.pkr.hcl
